server:
  port: 8088
a:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8083/eureka/

spring:
  application:
    name: service-zuul
  main:
    allow-bean-definition-overriding: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
#  max:
#    host:
#      connections: 500
#    host:
#      socket-timeout-millis: 60000
#      connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

